baseURL = 'https://getlocal-project-810af4.gitlab.io/simple/'
languageCode = 'en-us'
title = 'Simple CMS'
theme = 'ananke'

# Site configuration
[params]
  description = "A simple content management system built with Hugo"
  author = "Your Name"
  email = "your.email@example.com"

# Ananke theme configuration
[ananke]
  show_recent_posts = true

[ananke.social]
  icon_path = "ananke/socials/%s.svg"

[ananke.social.follow]
  new_window_icon = false
  networks = [
    "github",
    "linkedin",
    "twitter"
  ]

[ananke.social.share]
  icons = true
  sharetext = true
  networks = [
    "email",
    "facebook",
    "linkedin",
    "twitter"
  ]
  
# Build configuration
[build]
  writeStats = true

# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 20
  
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30
  
  [[menu.main]]
    name = "Admin"
    url = "/admin/"
    weight = 40

# Content configuration
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
